In [3]:
import numpy as np

In [4]:
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [5]:

print(np.__version__)

1.20.3


In [6]:
# NumPy Creating Arrays

In [7]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [9]:
# Dimensions in Arrays

# 0-D Arrays
arr = np.array(42)

print(arr)

42


In [10]:
# 1-D Arrays
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [11]:
# 2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
# 3-D arrays 
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
# Check Number of Dimensions
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
# Higher Dimensional Arrays 
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [16]:
# NumPy Array Indexing
   # Access Array Elements
    
arr = np.array([1, 2, 3, 4])
print(arr[2])

3


In [17]:
# Access 2-D Arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [18]:
# Access the element on the 2nd row, 5th column
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [19]:
#Access 3-D Arrays 
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [20]:
# Negative Indexing 

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [21]:
# NumPy Array Slicing 
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[3:])

[4 5 6 7]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [27]:
# Negative Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [29]:
 # Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [30]:
# NumPy Data Types

# Checking the Data Type of an Array
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [31]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [34]:
# Creating Arrays With a Defined Data Type

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype ,"string type")

[b'1' b'2' b'3' b'4']
|S1 string type


In [37]:
# NumPy Array Copy vs View
 #COPY:
    
arr = np.array([1, 2, 3, 4, 5,6,7,8,9])
x = arr.copy()
arr[0] = 79

print(arr)
print(x)

[79  2  3  4  5  6  7  8  9]
[1 2 3 4 5 6 7 8 9]


In [39]:
#VIEW: 
arr = np.array([1, 2, 3, 4, 5,6,7,8])
x = arr.view()
arr[0] = 69

print(arr)
print(x)

[69  2  3  4  5  6  7  8]
[69  2  3  4  5  6  7  8]


In [40]:
# Make Changes in the VIEW
arr = np.array([1, 2, 3, 4, 5,6,7,8,9])
x = arr.view()
x[0] = 89

print(arr)
print(x)

[89  2  3  4  5  6  7  8  9]
[89  2  3  4  5  6  7  8  9]


In [41]:
# Checking the if Array Owns its Data

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [42]:
# NumPy Array Shape
#Shape of an Array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [43]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [44]:
# NumPy Array Reshaping
 
#Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
#Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [47]:
# NumPy Array Iterating
#Iterating Arrays

arr = np.array([1, 2, 3,4,5,6])

for x in arr:
  print(x)


1
2
3
4
5
6


In [48]:
#Iterating 2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [49]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [50]:
#Iterating 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [52]:
#Iterate down to the scalars:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [54]:
#Iterating Arrays Using nditer()
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [55]:
#Joining NumPy Arrays
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [56]:
# Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [57]:
#Joining Arrays Using Stack Functions

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [58]:
#Stacking Along Rows
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [59]:
#Stacking Along Columns
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [60]:
#Stacking Along Height (depth)
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)


[[[1 4]
  [2 5]
  [3 6]]]


In [61]:
#NumPy Splitting Array
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [62]:
#Split Into Arrays
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [63]:
#Splitting 2-D Arrays

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [65]:
#Searching Arrays
arr = np.array([1, 2, 3, 4, 5, 4, 4,5,6,7])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [67]:
#Find the indexes where the values are even:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,10,22])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7, 8, 9], dtype=int64),)


In [69]:
#Find the indexes where the values are odd:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,11])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6, 8, 9], dtype=int64),)


In [70]:
#Search Sorted
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [72]:
#Sorting Arrays
arr = np.array([3, 2, 0, 1,4,6,34,45])

print(np.sort(arr))

[ 0  1  2  3  4  6 34 45]


In [74]:
#Sort the array alphabetically

arr = np.array(['banana', 'cherry', 'apple','kiwi'])

print(np.sort(arr))

['apple' 'banana' 'cherry' 'kiwi']


In [75]:
#Sort a boolean array:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [76]:
#Sorting a 2-D Array
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [77]:
#NumPy Filter Array


[41 43]


In [87]:
#Creating the Filter Array

In [88]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
